function build_threat_model()
%% BUILD_THREAT_MODEL - Phase A4 (System Objects engine): Rician + Threat + AWGN
% Split Digital Twin: [Tx: mod+RRC] -> [Rician] -> [Threat] -> [AWGN] -> [Rx: RRC+demod]
% Same validated engine as base/Rician links. Threats injected on the SHAPED IQ
% at the HIGH sample rate (symbol_rate * sps). All 8 threats implemented (Approach A,
% signal-level). params.active_threat selects; 'none' reproduces the A3 baseline.
%   Threats: jamming, noise_burst, path_loss, antenna_fault, spoofing, reactive_jamming,
%            benign_interference, sweeping_jammer
%
% sps-ADAPTATION (critical): timing-based threats now count SAMPLES, not symbols.
%   - noise_burst / antenna_fault / sweeping_jammer periods scaled by sps (period*sps, on*sps).
%   - reactive_jamming threshold scaled by 1/sps (per-sample energy is ~1/sps of
%     the symbol energy after RRC upsampling).
%
% SPOOFING FIX (2026-09-16): the previous implementation injected i.i.d.
% per-SAMPLE random QPSK-valued noise (randn(size(u))>0 per sample) -- this
% is NOT a coherent modulated signal, just wideband noise with a QPSK-shaped
% amplitude distribution. It had no real symbol-rate structure or pulse
% shaping, so it was spectrally near-indistinguishable from jamming/
% reactive_jamming/benign_interference (all additive i.i.d. noise variants) --
% root-caused as the reason spoofing recall stayed weak (53-79.5%) across
% every detector architecture tried (CNN, CNN+temporal-features, CNN-LSTM).
% Fixed here: spoofing now generates a REAL counterfeit bit stream, QPSK-
% modulates it, and RRC-pulse-shapes it with the SAME filter parameters as
% the legitimate Tx -- i.e. a genuine coherent spoofed carrier, exactly what
% "spoofing" is meant to model. This gives it actual spectral/temporal
% structure distinguishable from broadband noise threats, which the existing
% CNN spectrogram branch can learn directly (no new features required as a
% first step -- see PROJECT_LOG for the validation plan before adding any
% EVM/phase feature on top of this).

modelName = 'UAV_GCS_Threat_Link';

if ~exist('params.mat', 'file')
    error('params.mat not found. Run init_params.m first.');
end
S = load('params.mat');
p = S.params;
sps = p.sps;
sample_rate_high = p.symbol_rate * sps;   % RRC output / channel rate

if bdIsLoaded(modelName)
    close_system(modelName, 0);
end
new_system(modelName);
open_system(modelName);

fprintf('Building model "%s" (System Objects engine, threat: %s)...\n', ...
    modelName, p.active_threat);

%% ---- Add blocks ----
add_block('commrandsrc3/Bernoulli Binary Generator', ...
    [modelName '/BitSource'], 'Position', [30 100 90 140]);
add_block('simulink/User-Defined Functions/MATLAB Function', ...
    [modelName '/Tx'], 'Position', [150 95 250 145]);
add_block('simulink/User-Defined Functions/MATLAB Function', ...
    [modelName '/Rician'], 'Position', [300 95 390 145]);
add_block('simulink/User-Defined Functions/MATLAB Function', ...
    [modelName '/Threat'], 'Position', [440 95 530 145]);
add_block('commchan3/AWGN Channel', ...
    [modelName '/AWGN'], 'Position', [580 100 650 140]);
add_block('simulink/User-Defined Functions/MATLAB Function', ...
    [modelName '/Rx'], 'Position', [710 95 810 145]);

% Bit-stream logging (offline BER via delay-scan)
add_block('simulink/Sinks/To Workspace', ...
    [modelName '/tx_sink'], 'Position', [150 30 230 60]);
add_block('simulink/Sinks/To Workspace', ...
    [modelName '/rx_sink'], 'Position', [870 100 950 130]);

% IQ probes (for spectrogram in A6) — tap AFTER AWGN (matches build_link_model.m
% and build_rician_model.m: "received" IQ means post-channel-noise, so the
% spectrogram/RSSI actually reflect the configured SNR sweep point). FIXED
% 2026-09-19: previously tapped Threat/1 (pre-AWGN), which meant spectrograms
% and RSSI never varied with SNR at all -- only ground-truth BER did. See
% docs/DECISIONS.md D18.
add_block('simulink/Sinks/To Workspace', ...
    [modelName '/Tx_IQ'], 'Position', [300 30 380 60]);
add_block('simulink/Sinks/To Workspace', ...
    [modelName '/Rx_IQ'], 'Position', [580 180 660 210]);

%% ---- Inject Tx code (mod + RRC transmit) ----
sf_root = sfroot;
chart_tx = sf_root.find('-isa','Stateflow.EMChart','Path',[modelName '/Tx']);
chart_tx.Script = sprintf([ ...
    'function y = fcn(bits)\n' ...
    '%%#codegen\n' ...
    'persistent txf\n' ...
    'if isempty(txf)\n' ...
    '    txf = comm.RaisedCosineTransmitFilter(...\n' ...
    '        ''RolloffFactor'', %.6f, ...\n' ...
    '        ''FilterSpanInSymbols'', %d, ...\n' ...
    '        ''OutputSamplesPerSymbol'', %d);\n' ...
    'end\n' ...
    'sym = pskmod(bits, 4, pi/4, ''gray'', ''InputType'', ''bit'');\n' ...
    'y = txf(sym);\n' ...
    'end\n'], p.rolloff, p.filter_span, sps);

%% ---- Inject Rician code (shaped IQ, HIGH sample rate) ----
chart_ric = sf_root.find('-isa','Stateflow.EMChart','Path',[modelName '/Rician']);
k_linear = 10^(p.rician_k / 10);
chart_ric.Script = sprintf([ ...
    'function y = fcn(u)\n' ...
    '%%#codegen\n' ...
    'persistent rc\n' ...
    'if isempty(rc)\n' ...
    '    rc = comm.RicianChannel(''KFactor'', %.6f, ...\n' ...
    '        ''MaximumDopplerShift'', %.6f, ''SampleRate'', %g);\n' ...
    'end\n' ...
    'y = rc(u);\n' ...
    'end\n'], k_linear, p.fd_max, sample_rate_high);

%% ---- Inject Threat code (Approach A, sps-adapted) ----
chart_th = sf_root.find('-isa','Stateflow.EMChart','Path',[modelName '/Threat']);
if contains(p.active_threat, '+')
    % Combined threat (D32), e.g. 'jamming+path_loss': components applied in sequence
    chart_th.Script = combined_threat_script(p, sps);
else
switch lower(p.active_threat)

    case 'jamming'
        % Barrage jamming: continuous additive wideband complex Gaussian noise.
        jammerPower = 10^(p.jsr_db / 10);
        chart_th.Script = sprintf([ ...
            'function y = fcn(u)\n' ...
            '%%#codegen\n' ...
            'jammerPower = %.6f;\n' ...
            'n = sqrt(jammerPower/2) * (randn(size(u)) + 1i*randn(size(u)));\n' ...
            'y = u + n;\n' ...
            'end\n'], jammerPower);

    case 'noise_burst'
        % Bursty jamming: additive noise gated ON/OFF. Period scaled to SAMPLES.
        jammerPower  = 10^(p.jsr_db / 10);
        period_samp  = p.burst_period * sps;
        onSamp       = round(p.burst_duty * period_samp);
        chart_th.Script = sprintf([ ...
            'function y = fcn(u)\n' ...
            '%%#codegen\n' ...
            'persistent k\n' ...
            'if isempty(k); k = 0; end\n' ...
            'jammerPower = %.6f;\n' ...
            'N = numel(u);\n' ...
            'y = u;\n' ...
            'for i = 1:N\n' ...
            '    phase = mod(k, %d);\n' ...
            '    if phase < %d\n' ...
            '        n = sqrt(jammerPower/2) * (randn + 1i*randn);\n' ...
            '        y(i) = u(i) + n;\n' ...
            '    end\n' ...
            '    k = k + 1;\n' ...
            'end\n' ...
            'end\n'], jammerPower, period_samp, onSamp);

    case 'path_loss'
        % Path Loss: constant attenuation. Multiplicative -> rate-independent.
        pathLossLinear = 10^(-p.path_loss_db / 20);
        chart_th.Script = sprintf([ ...
            'function y = fcn(u)\n' ...
            '%%#codegen\n' ...
            'pathLossLinear = %.6f;\n' ...
            'y = u * pathLossLinear;\n' ...
            'end\n'], pathLossLinear);

    case 'antenna_fault'
        % Antenna Fault: severe attenuation gated ON/OFF. Period scaled to SAMPLES.
        faultLinear = 10^(-p.fault_atten_db / 20);
        period_samp = p.fault_period * sps;
        onSamp      = round(p.fault_duty * period_samp);
        chart_th.Script = sprintf([ ...
            'function y = fcn(u)\n' ...
            '%%#codegen\n' ...
            'persistent k\n' ...
            'if isempty(k); k = 0; end\n' ...
            'faultLinear = %.6f;\n' ...
            'N = numel(u);\n' ...
            'y = u;\n' ...
            'for i = 1:N\n' ...
            '    phase = mod(k, %d);\n' ...
            '    if phase < %d\n' ...
            '        y(i) = u(i) * faultLinear;\n' ...
            '    end\n' ...
            '    k = k + 1;\n' ...
            'end\n' ...
            'end\n'], faultLinear, period_samp, onSamp);

    case 'spoofing'
        % SPOOFING (FIXED 2026-09-16): genuine coherent counterfeit QPSK
        % carrier, RRC pulse-shaped with the SAME filter params as the
        % legitimate Tx, at the correct symbol rate -- NOT per-sample i.i.d.
        % noise. spoofAmp still controls relative power via spoof_sir_db
        % (same convention as before: amplitude ratio between legit signal
        % and spoofed carrier).
        %
        % nSym = N/sps assumes u arrives as a whole-frame vector (matches
        % samples_per_frame = symbols_per_frame * sps, consistent with how
        % every other threat case here already indexes u by SAMPLES derived
        % from period*sps). A persistent RaisedCosineTransmitFilter instance
        % (separate from Tx's own txf) carries filter state across calls,
        % exactly like Tx's own persistent filter does.
        spoofAmp = 10^(p.spoof_sir_db / 20);
        chart_th.Script = sprintf([ ...
            'function y = fcn(u)\n' ...
            '%%#codegen\n' ...
            'persistent spoof_txf\n' ...
            'if isempty(spoof_txf)\n' ...
            '    spoof_txf = comm.RaisedCosineTransmitFilter(...\n' ...
            '        ''RolloffFactor'', %.6f, ...\n' ...
            '        ''FilterSpanInSymbols'', %d, ...\n' ...
            '        ''OutputSamplesPerSymbol'', %d);\n' ...
            'end\n' ...
            'spoofAmp = %.6f;\n' ...
            'sps_local = %d;\n' ...
            'N = numel(u);\n' ...
            'nSym = floor(N / sps_local);\n' ...
            'spoofBits = randi([0 1], nSym*2, 1);\n' ...
            'spoofSym = pskmod(spoofBits, 4, pi/4, ''gray'', ''InputType'', ''bit'');\n' ...
            'spoofSig = spoof_txf(spoofSym);\n' ...
            'y = u + spoofAmp * spoofSig(1:N);\n' ...
            'end\n'], p.rolloff, p.filter_span, sps, spoofAmp, sps);

    case 'reactive_jamming'
        % Reactive Jamming: energy-triggered smart jammer. Threshold scaled by 1/sps
        % (per-sample energy is ~1/sps of symbol energy after RRC upsampling).
        jammerPower = 10^(p.jsr_db / 10);
        threshold   = p.reactive_threshold / sps;
        chart_th.Script = sprintf([ ...
            'function y = fcn(u)\n' ...
            '%%#codegen\n' ...
            'jammerPower = %.6f;\n' ...
            'threshold = %.6f;\n' ...
            'N = numel(u);\n' ...
            'y = u;\n' ...
            'for i = 1:N\n' ...
            '    if abs(u(i))^2 > threshold\n' ...
            '        n = sqrt(jammerPower/2) * (randn + 1i*randn);\n' ...
            '        y(i) = u(i) + n;\n' ...
            '    end\n' ...
            'end\n' ...
            'end\n'], jammerPower, threshold);

    case 'benign_interference'
        % Benign Interference: weak, continuous, NON-malicious in-band noise
        % (e.g. a neighboring WiFi/ISM device). Same additive mechanism as
        % jamming, but at much lower power -- benign_int_db sits far below the
        % jamming power range (-10 to -2 dB vs jamming's 0-16 dB), so this
        % class never overlaps the attack range. Exists to give the CNN a
        % "looks-like-something-but-isn't-an-attack" class for FAR measurement.
        jammerPower = 10^(p.benign_int_db / 10);
        chart_th.Script = sprintf([ ...
            'function y = fcn(u)\n' ...
            '%%#codegen\n' ...
            'jammerPower = %.6f;\n' ...
            'N = numel(u);\n' ...
            'n = sqrt(jammerPower/2) * (randn(N,1) + 1i*randn(N,1));\n' ...
            'y = u + n;\n' ...
            'end\n'], jammerPower);

    case 'sweeping_jammer'
        % Sweeping Jammer: same power as barrage jamming (jsr_db) but only
        % dwells on our channel a fraction of the time (sweep_duty), on a
        % longer cycle (sweep_period) than noise_burst -- models a jammer
        % that spends most of its time scanning OTHER channels and briefly
        % lands on ours. Period scaled to SAMPLES (same convention as
        % noise_burst/antenna_fault).
        jammerPower = 10^(p.jsr_db / 10);
        period_samp = p.sweep_period * sps;
        onSamp      = round(p.sweep_duty * period_samp);
        chart_th.Script = sprintf([ ...
            'function y = fcn(u)\n' ...
            '%%#codegen\n' ...
            'persistent k\n' ...
            'if isempty(k); k = 0; end\n' ...
            'jammerPower = %.6f;\n' ...
            'N = numel(u);\n' ...
            'y = u;\n' ...
            'for i = 1:N\n' ...
            '    phase = mod(k, %d);\n' ...
            '    if phase < %d\n' ...
            '        n = sqrt(jammerPower/2) * (randn + 1i*randn);\n' ...
            '        y(i) = u(i) + n;\n' ...
            '    end\n' ...
            '    k = k + 1;\n' ...
            'end\n' ...
            'end\n'], jammerPower, period_samp, onSamp);

    otherwise   % 'none' -> passthrough (reproduces A3 Rician baseline)
        chart_th.Script = sprintf([ ...
            'function y = fcn(u)\n' ...
            '%%#codegen\n' ...
            'y = u;\n' ...
            'end\n']);
end
end

%% ---- Inject Rx code (RRC receive + demod) ----
chart_rx = sf_root.find('-isa','Stateflow.EMChart','Path',[modelName '/Rx']);
chart_rx.Script = sprintf([ ...
    'function bits = fcn(u)\n' ...
    '%%#codegen\n' ...
    'persistent rxf\n' ...
    'if isempty(rxf)\n' ...
    '    rxf = comm.RaisedCosineReceiveFilter(...\n' ...
    '        ''RolloffFactor'', %.6f, ...\n' ...
    '        ''FilterSpanInSymbols'', %d, ...\n' ...
    '        ''InputSamplesPerSymbol'', %d, ...\n' ...
    '        ''DecimationFactor'', %d);\n' ...
    'end\n' ...
    'sym = rxf(u);\n' ...
    'bits = pskdemod(sym, 4, pi/4, ''gray'', ''OutputType'', ''bit'');\n' ...
    'end\n'], p.rolloff, p.filter_span, sps, sps);

%% ---- Configure blocks ----
Tsym = 1 / p.symbol_rate;
set_param([modelName '/BitSource'], ...
    'ProbabilityOfZero', '0.5', ...
    'SampleTime', num2str(Tsym / p.bits_per_symbol), ...
    'SamplesPerFrame', num2str(p.frame_length));

% AWGN at the high (sps×) rate: SNR + SignalPower corrected for oversampling
snr0 = p.EbNo_dB(1) + 10*log10(p.bits_per_symbol) - 10*log10(sps);
set_param([modelName '/AWGN'], ...
    'SNR', num2str(snr0), ...
    'SignalPower', num2str(1/sps));

% Workspace sinks — Array format for clean extraction
set_param([modelName '/tx_sink'], 'VariableName', 'tx_bits_out', 'SaveFormat', 'Array');
set_param([modelName '/rx_sink'], 'VariableName', 'rx_bits_out', 'SaveFormat', 'Array');
set_param([modelName '/Tx_IQ'], 'VariableName', 'Tx_IQ', 'SaveFormat', 'Array');
set_param([modelName '/Rx_IQ'], 'VariableName', 'Rx_IQ', 'SaveFormat', 'Array');

%% ---- Wire it up ----
add_line(modelName, 'BitSource/1', 'Tx/1',     'autorouting','on');
add_line(modelName, 'Tx/1',       'Rician/1',  'autorouting','on');
add_line(modelName, 'Rician/1',   'Threat/1',  'autorouting','on');
add_line(modelName, 'Threat/1',   'AWGN/1',    'autorouting','on');
add_line(modelName, 'AWGN/1',     'Rx/1',      'autorouting','on');

% Logging taps
add_line(modelName, 'BitSource/1', 'tx_sink/1', 'autorouting','on');
add_line(modelName, 'Rx/1',        'rx_sink/1', 'autorouting','on');
add_line(modelName, 'Tx/1',        'Tx_IQ/1',   'autorouting','on');
add_line(modelName, 'AWGN/1',      'Rx_IQ/1',   'autorouting','on');

%% ---- Solver settings ----
set_param(modelName, 'SolverType', 'Fixed-step', ...
    'Solver', 'FixedStepDiscrete', ...
    'StopTime', '0.01');

%% ---- Save ----
if ~exist('models', 'dir'); mkdir('models'); end
save_system(modelName, ['models/' modelName '.slx']);
fprintf('Model saved to models/%s.slx\n', modelName);
fprintf('Done. Threat model (System Objects engine, threat=%s, JSR=%.1f dB, K=%.1f dB, fd=%.1f Hz, sps=%d).\n', ...
    p.active_threat, p.jsr_db, p.rician_k, p.fd_max, sps);
end

function script = combined_threat_script(p, sps)
%COMBINED_THREAT_SCRIPT  MATLAB Function body for a combined threat 'a+b[+c]' (D32).
%   Signal-side components (path_loss, antenna_fault) act first, so they attenuate
%   only our signal; additive components follow. Each component uses the same
%   model and parameters as its single-threat case, with its own persistent state.
parts = strsplit(lower(p.active_threat), '+');
order = [parts(ismember(parts, {'path_loss','antenna_fault'})), parts(~ismember(parts, {'path_loss','antenna_fault'}))];
pers = {}; body = {};
for i = 1:numel(order)
    c = order{i};
    switch c
        case 'path_loss'
            body{end+1} = sprintf('y = y * %.6f;\n', 10^(-p.path_loss_db/20)); %#ok<AGROW>
        case 'antenna_fault'
            ps = p.fault_period * sps; on = round(p.fault_duty * ps);
            pers{end+1} = 'k_af'; %#ok<AGROW>
            body{end+1} = sprintf(['for i = 1:numel(y)\n    if mod(k_af, %d) < %d\n        y(i) = y(i) * %.6f;\n    end\n' ...
                '    k_af = k_af + 1;\nend\n'], ps, on, 10^(-p.fault_atten_db/20)); %#ok<AGROW>
        case 'jamming'
            body{end+1} = sprintf('y = y + sqrt(%.6f/2) * (randn(size(y)) + 1i*randn(size(y)));\n', 10^(p.jsr_db/10)); %#ok<AGROW>
        case 'benign_interference'
            body{end+1} = sprintf('y = y + sqrt(%.6f/2) * (randn(size(y)) + 1i*randn(size(y)));\n', 10^(p.benign_int_db/10)); %#ok<AGROW>
        case 'noise_burst'
            ps = p.burst_period * sps; on = round(p.burst_duty * ps);
            pers{end+1} = 'k_nb'; %#ok<AGROW>
            body{end+1} = sprintf(['for i = 1:numel(y)\n    if mod(k_nb, %d) < %d\n' ...
                '        y(i) = y(i) + sqrt(%.6f/2) * (randn + 1i*randn);\n    end\n    k_nb = k_nb + 1;\nend\n'], ...
                ps, on, 10^(p.jsr_db/10)); %#ok<AGROW>
        case 'sweeping_jammer'
            ps = p.sweep_period * sps; on = round(p.sweep_duty * ps);
            pers{end+1} = 'k_sw'; %#ok<AGROW>
            body{end+1} = sprintf(['for i = 1:numel(y)\n    if mod(k_sw, %d) < %d\n' ...
                '        y(i) = y(i) + sqrt(%.6f/2) * (randn + 1i*randn);\n    end\n    k_sw = k_sw + 1;\nend\n'], ...
                ps, on, 10^(p.jsr_db/10)); %#ok<AGROW>
        case 'reactive_jamming'
            body{end+1} = sprintf(['for i = 1:numel(y)\n    if abs(y(i))^2 > %.6f\n' ...
                '        y(i) = y(i) + sqrt(%.6f/2) * (randn + 1i*randn);\n    end\nend\n'], ...
                p.reactive_threshold / sps, 10^(p.jsr_db/10)); %#ok<AGROW>
        case 'spoofing'
            pers{end+1} = 'spoof_txf'; %#ok<AGROW>
            body{end+1} = sprintf(['if isempty(spoof_txf)\n    spoof_txf = comm.RaisedCosineTransmitFilter(''RolloffFactor'', %.6f, ' ...
                '''FilterSpanInSymbols'', %d, ''OutputSamplesPerSymbol'', %d);\nend\n' ...
                'nSym = floor(numel(y) / %d);\nspoofSym = pskmod(randi([0 1], nSym*2, 1), 4, pi/4, ''gray'', ''InputType'', ''bit'');\n' ...
                'spoofSig = spoof_txf(spoofSym);\ny = y + %.6f * spoofSig(1:numel(y));\n'], ...
                p.rolloff, p.filter_span, sps, sps, 10^(p.spoof_sir_db/20)); %#ok<AGROW>
        otherwise
            error('combined_threat_script: unsupported component ''%s''', c);
    end
end
head = 'function y = fcn(u)\n%%#codegen\n';
for i = 1:numel(pers)
    if strcmp(pers{i}, 'spoof_txf')
        head = [head 'persistent spoof_txf\n']; %#ok<AGROW>
    else
        head = [head sprintf('persistent %s\nif isempty(%s); %s = 0; end\n', pers{i}, pers{i}, pers{i})]; %#ok<AGROW>
    end
end
script = [sprintf(head) 'y = u;' newline strjoin(body, '') 'end' newline];
end
