%% MEASURE_KPI3_RECOVERY_TIME.m — proposal KPI #3: DQN vs Rule-Based decision speed
%
% REFRAMED (2026-09-16): the original version of this script simulated
% "recovery cycles" with a mock BER-halving loop that never called sim() or
% consulted either policy's actual action choice -- the reported cycle counts
% were identical for DQN and Rule-Based regardless of which was "tested",
% because nothing in the loop actually depended on the policy at all.
%
% Root cause of why "cycles" was the wrong framing to begin with: in this
% system, every countermeasure action applies a FIXED, ONE-SHOT dB mitigation
% (action_mitigation_db, see rule_based_policy.m / run_closed_loop_*.m) to the
% threat's severity field. Both DQN and Rule-Based are deterministic policies
% -- given a fixed state, each picks exactly one action and converges
% immediately. There is no real iterative "cycles to converge" dynamic in
% this architecture to measure; a script that reports one anyway is
% necessarily simulating something the system doesn't actually do.
%
% What DOES meaningfully differ between the two policies, and IS already
% measured with real data, is DECISION SPEED: Rule-Based is a lookup table
% (a few dB and a switch-case -- effectively instant); DQN is a real neural
% network forward pass (a few ms). This script measures that directly:
%   - Rule-based latency: REAL timed call to rule_based_policy.m per threat
%     (not mocked -- actually executes the real lookup and times it)
%   - DQN latency + rule agreement: pulled from
%     results/closed_loop_diagnostic_report.txt, generated by
%     run_closed_loop_diagnostic.m -- real Simulink + real CNN + real DQN
%     inference. Rerun automatically here if missing/stale.
%     PROJECT_LOG.md). Rerun automatically here if missing/stale.
%
% This reframing changes WHAT is measured (decision latency, not cycles) to
% match what the system actually does, rather than inventing dynamics that
% aren't there. It does not simulate anything new -- every number in the
% output either comes from a live rule_based_policy.m call made in this run,
% or from the diagnostic report's own real Simulink-backed measurements.
%
% Output: results/kpi3_measurement.txt

close all; clc;
fprintf('=== KPI #3: Decision Speed (DQN vs Rule-Based) ===\n\n');

MAX_STALE_DAYS = 0.5;   % 12 hours -- the pipeline changes faster than days

%% 1. Ensure a fresh diagnostic report exists (real Simulink+CNN+DQN data)
diag_path = 'results/closed_loop_diagnostic_report.txt';
need_rerun = ~exist(diag_path, 'file');
if ~need_rerun
    d = dir(diag_path);
    need_rerun = (now - datenum(d.date)) > MAX_STALE_DAYS;
end
if need_rerun
    fprintf('No fresh %s found -- running run_closed_loop_diagnostic...\n', diag_path);
    run_closed_loop_diagnostic;
end

txt = fileread(diag_path);

%% 2. Parse per-threat blocks (split on the block marker, then regex each block)
blocks = strsplit(txt, '--- Threat: ');
blocks(1) = [];   % first split chunk is header text before the first threat

threats = {}; dqn_latency_ms = []; rule_action = {}; agrees = []; recovery_pct = [];

for i = 1:numel(blocks)
    b = blocks{i};
    name_tok = regexp(b, '^(\w+) ---', 'tokens', 'once');
    if isempty(name_tok), continue; end
    threats{end+1} = name_tok{1}; %#ok<AGROW>

    dqn_tok = regexp(b, 'DQN decision: \S+ \(([\d.]+) ms\)', 'tokens', 'once');
    dqn_latency_ms(end+1) = str2double(dqn_tok{1}); %#ok<AGROW>

    rule_tok = regexp(b, 'Rule-based would choose: (\S+) \| DQN agrees: (\d)', 'tokens', 'once');
    rule_action{end+1} = rule_tok{1}; %#ok<AGROW>
    agrees(end+1) = str2double(rule_tok{2}); %#ok<AGROW>

    rec_tok = regexp(b, 'recovery=([\d.-]+)%', 'tokens', 'once');
    recovery_pct(end+1) = str2double(rec_tok{1}); %#ok<AGROW>
end

n = numel(threats);
if n == 0
    error('Could not parse any threat blocks from %s -- has its report format changed?', diag_path);
end
fprintf('Parsed %d threats from %s\n\n', n, diag_path);

%% 3. Time the REAL rule_based_policy.m call per threat (actual execution, not mocked)
rule_latency_ms = zeros(1, n);
N_TIMING_REPEATS = 1000;   % lookup is sub-ms; repeat and average for a stable reading
for i = 1:n
    t0 = tic;
    for r = 1:N_TIMING_REPEATS
        [~, ~] = rule_based_policy(threats{i});
    end
    rule_latency_ms(i) = (toc(t0) / N_TIMING_REPEATS) * 1000;
end

%% 4. Report
report = {};
report{end+1} = '=== KPI #3: Decision Speed (DQN vs Rule-Based) ===';
report{end+1} = sprintf('Generated: %s', datestr(now));
report{end+1} = '';
report{end+1} = 'NOTE: "recovery cycles" is not a meaningful metric for this architecture --';
report{end+1} = 'every action applies a fixed one-shot dB mitigation and both policies are';
report{end+1} = 'deterministic, so both converge in exactly 1 decision regardless of policy.';
report{end+1} = 'The metric that actually differs is DECISION LATENCY (real, timed below).';
report{end+1} = '';
report{end+1} = sprintf('%-22s %14s %14s %10s %10s', 'Threat', 'DQN (ms)', 'Rule (ms)', 'Agree?', 'Recov%');
for i = 1:n
    report{end+1} = sprintf('%-22s %14.3f %14.5f %10s %9.1f%%', ...
        threats{i}, dqn_latency_ms(i), rule_latency_ms(i), string(logical(agrees(i))), recovery_pct(i));
end
report{end+1} = '';
report{end+1} = sprintf('Mean DQN latency:  %.3f ms', mean(dqn_latency_ms));
report{end+1} = sprintf('Mean Rule latency: %.5f ms', mean(rule_latency_ms));
report{end+1} = sprintf('Speed ratio: Rule-Based is ~%.0fx faster than DQN (lookup table vs neural net inference)', ...
    mean(dqn_latency_ms) / mean(rule_latency_ms));
report{end+1} = sprintf('DQN-vs-Rule agreement: %d/%d (%.1f%%)', sum(agrees), n, 100*mean(agrees));
report{end+1} = '';
report{end+1} = 'Interpretation: Rule-Based is effectively instant (a dB lookup); DQN costs a';
report{end+1} = 'few ms of real neural-network inference. This is the genuine speed trade-off';
report{end+1} = 'of using a learned policy over a static one in this system -- DQN''s value is';
report{end+1} = 'not faster convergence (both converge in 1 step) but rather the potential to';
report{end+1} = 'learn better-than-rule-based action choices from data (measured separately as';
report{end+1} = 'recovery%% and agreement rate above).';

if ~exist('results', 'dir'), mkdir('results'); end
fid = fopen('results/kpi3_measurement.txt', 'w');
for i = 1:numel(report), fprintf(fid, '%s\n', report{i}); end
fclose(fid);
for i = 1:numel(report), fprintf('%s\n', report{i}); end
fprintf('\nSaved results/kpi3_measurement.txt\n');
fprintf('\n=== KPI #3 Complete ===\n');