function build_rician_model()
%% BUILD_RICIAN_MODEL - Phase A3 (System Objects engine): Rician + AWGN + pulse shaping
% Split Digital Twin: [Tx: mod+RRC] -> [Rician graphical] -> [AWGN graphical] -> [Rx: RRC+demod]
% Same validated Tx/Rx engine as base link; adds one Rician block on the shaped IQ.
% Rician runs at the HIGH sample rate (symbol_rate * sps) so Doppler is correct.
% Expected: BER ~1.4x above AWGN theory (fading degradation) = motivation for recovery.

modelName = 'UAV_GCS_Rician_Link';

if ~exist('params.mat', 'file')
    error('params.mat not found. Run init_params.m first.');
end
S = load('params.mat');
p = S.params;
sps = p.sps;

if bdIsLoaded(modelName)
    close_system(modelName, 0);
end
new_system(modelName);
open_system(modelName);

fprintf('Building model "%s" (System Objects engine, sps=%d)...\n', modelName, sps);

%% ---- Add blocks ----
add_block('commrandsrc3/Bernoulli Binary Generator', ...
    [modelName '/BitSource'], 'Position', [30 100 90 140]);
add_block('simulink/User-Defined Functions/MATLAB Function', ...
    [modelName '/Tx'], 'Position', [150 95 250 145]);
add_block('simulink/User-Defined Functions/MATLAB Function', ...
    [modelName '/Rician'], 'Position', [300 95 390 145]);
add_block('commchan3/AWGN Channel', ...
    [modelName '/AWGN'], 'Position', [440 100 510 140]);
add_block('simulink/User-Defined Functions/MATLAB Function', ...
    [modelName '/Rx'], 'Position', [570 95 670 145]);

% Bit-stream logging (offline BER via delay-scan)
add_block('simulink/Sinks/To Workspace', ...
    [modelName '/tx_sink'], 'Position', [150 30 230 60]);
add_block('simulink/Sinks/To Workspace', ...
    [modelName '/rx_sink'], 'Position', [730 100 810 130]);

% IQ probes (for spectrogram in A6)
add_block('simulink/Sinks/To Workspace', ...
    [modelName '/Tx_IQ'], 'Position', [300 30 380 60]);
add_block('simulink/Sinks/To Workspace', ...
    [modelName '/Rx_IQ'], 'Position', [440 180 520 210]);

%% ---- Inject Tx code (mod + RRC transmit) ----
sf_root = sfroot;
chart_tx = sf_root.find('-isa','Stateflow.EMChart','Path',[modelName '/Tx']);
chart_tx.Script = sprintf([ ...
    'function y = fcn(bits)\n' ...
    '%%#codegen\n' ...
    'persistent txf\n' ...
    'if isempty(txf)\n' ...
    '    txf = comm.RaisedCosineTransmitFilter(...\n' ...
    '        ''RolloffFactor'', %.6f, ...\n' ...
    '        ''FilterSpanInSymbols'', %d, ...\n' ...
    '        ''OutputSamplesPerSymbol'', %d);\n' ...
    'end\n' ...
    'sym = pskmod(bits, 4, pi/4, ''gray'', ''InputType'', ''bit'');\n' ...
    'y = txf(sym);\n' ...
    'end\n'], p.rolloff, p.filter_span, sps);

%% ---- Inject Rician code (on shaped IQ, at HIGH sample rate) ----
chart_ric = sf_root.find('-isa','Stateflow.EMChart','Path',[modelName '/Rician']);
k_linear = 10^(p.rician_k / 10);
sample_rate_high = p.symbol_rate * sps;   % RRC output rate
chart_ric.Script = sprintf([ ...
    'function y = fcn(u)\n' ...
    '%%#codegen\n' ...
    'persistent rc\n' ...
    'if isempty(rc)\n' ...
    '    rc = comm.RicianChannel(''KFactor'', %.6f, ...\n' ...
    '        ''MaximumDopplerShift'', %.6f, ''SampleRate'', %g);\n' ...
    'end\n' ...
    'y = rc(u);\n' ...
    'end\n'], k_linear, p.fd_max, sample_rate_high);

%% ---- Inject Rx code (RRC receive + demod) ----
chart_rx = sf_root.find('-isa','Stateflow.EMChart','Path',[modelName '/Rx']);
chart_rx.Script = sprintf([ ...
    'function bits = fcn(u)\n' ...
    '%%#codegen\n' ...
    'persistent rxf\n' ...
    'if isempty(rxf)\n' ...
    '    rxf = comm.RaisedCosineReceiveFilter(...\n' ...
    '        ''RolloffFactor'', %.6f, ...\n' ...
    '        ''FilterSpanInSymbols'', %d, ...\n' ...
    '        ''InputSamplesPerSymbol'', %d, ...\n' ...
    '        ''DecimationFactor'', %d);\n' ...
    'end\n' ...
    'sym = rxf(u);\n' ...
    'bits = pskdemod(sym, 4, pi/4, ''gray'', ''OutputType'', ''bit'');\n' ...
    'end\n'], p.rolloff, p.filter_span, sps, sps);

%% ---- Configure blocks ----
Tsym = 1 / p.symbol_rate;
set_param([modelName '/BitSource'], ...
    'ProbabilityOfZero', '0.5', ...
    'SampleTime', num2str(Tsym / p.bits_per_symbol), ...
    'SamplesPerFrame', num2str(p.frame_length));

% AWGN at the high (sps×) rate: SNR + SignalPower corrected for oversampling
snr0 = p.EbNo_dB(1) + 10*log10(p.bits_per_symbol) - 10*log10(sps);
set_param([modelName '/AWGN'], ...
    'SNR', num2str(snr0), ...
    'SignalPower', num2str(1/sps));

% Workspace sinks — Array format for clean extraction
set_param([modelName '/tx_sink'], 'VariableName', 'tx_bits_out', 'SaveFormat', 'Array');
set_param([modelName '/rx_sink'], 'VariableName', 'rx_bits_out', 'SaveFormat', 'Array');
set_param([modelName '/Tx_IQ'], 'VariableName', 'Tx_IQ', 'SaveFormat', 'Array');
set_param([modelName '/Rx_IQ'], 'VariableName', 'Rx_IQ', 'SaveFormat', 'Array');

%% ---- Wire it up ----
add_line(modelName, 'BitSource/1', 'Tx/1',     'autorouting','on');
add_line(modelName, 'Tx/1',       'Rician/1',  'autorouting','on');
add_line(modelName, 'Rician/1',   'AWGN/1',    'autorouting','on');
add_line(modelName, 'AWGN/1',     'Rx/1',      'autorouting','on');

% Logging taps
add_line(modelName, 'BitSource/1', 'tx_sink/1', 'autorouting','on');
add_line(modelName, 'Rx/1',        'rx_sink/1', 'autorouting','on');
add_line(modelName, 'Tx/1',        'Tx_IQ/1',   'autorouting','on');
add_line(modelName, 'AWGN/1',      'Rx_IQ/1',   'autorouting','on');

%% ---- Solver settings ----
set_param(modelName, 'SolverType', 'Fixed-step', ...
    'Solver', 'FixedStepDiscrete', ...
    'StopTime', '0.01');

%% ---- Save ----
if ~exist('models', 'dir'); mkdir('models'); end
save_system(modelName, ['models/' modelName '.slx']);
fprintf('Model saved to models/%s.slx\n', modelName);
fprintf('Done. Rician+AWGN link (System Objects engine, K=%.1f dB, fd=%.1f Hz, sps=%d).\n', ...
    p.rician_k, p.fd_max, sps);
end